export const objects = [
    {
        id: 'js1',
        customer: 'ООО "ГЕНЕЗИС"',
        name: 'Генезис',
        fullname: 'Поликлиника "Генезис" в Мирном',
        image:'assets/genesis.png',
        video:'back.mp4',
        title:'genesis',
        location: 'Cимферопольский р-н, с. Мирное, ул. Луговая, 16/2',
        // square: '',
        contract: 'Генеральный подряд',
        time: '201? - наши дни',
        videocode: 'KkPOh43_C0k?si=wFXi87z0ivV1-J-f'
    },
    {
        id: 'js2',
        customer: 'ООО "ЛОЦМАН"',
        name: 'Лоцман',
        fullname: 'Торговый Центр "Лоцман"',
        image:'assets/locman.jpg',
        video:'back.mp4',
        title:'locman',
        location: 'г. Симферополь, ул. Севастопольская, 31Е',
        contract: 'Генеральный подряд',
        time: '202? - наши дни',
        videocode: 'X-BaLKRofx4?si=kRIZwOgtMpKQMeQP'

    },
    {
        id: 'js3',
        customer: 'ООО "ЛАДА Симферополь"',
        name: 'Автосалон Лада',
        fullname: 'Автосалон Лада',
        image:'assets/lada.png',
        video:'back.mp4',
        title:'lada',
        time: '202? - наши дни',

    },
    {
        id: 'js4',
        customer: 'ООО "ОЗЕРНЫЙ"',
        name: 'Озерный',
        fullname: 'Коттеджный поселок "Озерный"',
        image: 'assets/ozernyi.png',
        video: 'back.mp4',
        location: 'село Белоглинка, Мирновское сельское поселение, Симферопольский район, Республика Крым',
        contract: 'Генеральный подряд',
        title:'ozerniy',
        time: '202? - наши дни',
        videocode: 'nci6Z_PAmE0?si=SgJ00B8u892jGh2W'
    },
    {
        id: 'js5',
        customer: 'ООО "ГЕНЕЗИС"',
        name: 'Генезис',
        fullname: 'Поликлиника "Генезис" в Мирном 2.0',
        image:'assets/genesis.png',
        video:'back.mp4',
        contract: 'Генеральный подряд',
        title:'genesis2.0',
    },
    {
        id: 'js6',
        customer: 'ООО "Олегор',
        name: 'Олегор',
        fullname: 'Заправка "Олегор"',
        //image:'assets/ozernyi.png',
        video:'back.mp4',
        contract: 'В разработке',
        title:'olegor',
    },
]
